[package]
name = "skelly"
version = "0.1.0"
authors = ["Lucas Newcomb <pantsbabyy@gmail.com>"]
description = """
A simple command line tool for using and managing skeleton projects
"""
documentation = "https://github.com/pants721/skelly"
homepage = "https://github.com/pants721/skelly"
repository = "https://github.com/pants721/skelly"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
clap = {version = "4.1.8", features = [ "derive" ]}
anyhow = "1.0.69"
colored = "2.0.0"

[[bin]]
name = "sk"
path = "src/main.rs"
