[package]
name = "skelly"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
keywords = ["cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
clap = {version = "4.1.8", features = [ "derive" ]}
anyhow = "1.0.69"
colored = "2.0.0"

[[bin]]
name = "sk"
path = "src/main.rs"
